backend:
  name: github
  repo: marvinjude/kirk-gatsby
media_folder: static/assets
extension: json
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }